// generated by bin/module-indexer.js
import codeIsAPaintbrush from './code-is-a-paintbrush.mdx';
import computerObservingItself from './computer-observing-itself.mdx';
import events from './events.mdx';
import infiniteChaos from './infinite-chaos.mdx';

export default {
  "code-is-a-paintbrush": codeIsAPaintbrush,
  "computer-observing-itself": computerObservingItself,
  "events": events,
  "infinite-chaos": infiniteChaos
};
