// generated by bin/module-indexer.js
import * as area715 from './area715.js';
import * as circleClock from './circle-clock.js';
import * as circuit from './circuit.js';
import * as cmyDance from './cmy-dance.js';
import * as diamonds from './diamonds.js';
import * as dizzyWaves from './dizzy-waves.js';
import * as drawbot from './drawbot.js';
import * as fittestBubbleBath from './fittest-bubble-bath.js';
import * as illusions from './illusions.js';
import * as infiniteChaos from './infinite-chaos.js';
import * as lookAbove from './look-above.js';
import * as lorenz from './lorenz.js';
import * as manifest from './manifest.js';
import * as revolutions from './revolutions.js';
import * as scales from './scales.js';
import * as solar from './solar.js';
import * as spinnySquares from './spinny-squares.js';
import * as squircle from './squircle.js';
import * as vintage from './vintage.js';

export default {
  "area715": area715,
  "circle-clock": circleClock,
  "circuit": circuit,
  "cmy-dance": cmyDance,
  "diamonds": diamonds,
  "dizzy-waves": dizzyWaves,
  "drawbot": drawbot,
  "fittest-bubble-bath": fittestBubbleBath,
  "illusions": illusions,
  "infinite-chaos": infiniteChaos,
  "look-above": lookAbove,
  "lorenz": lorenz,
  "manifest": manifest,
  "revolutions": revolutions,
  "scales": scales,
  "solar": solar,
  "spinny-squares": spinnySquares,
  "squircle": squircle,
  "vintage": vintage
};
